title: "Go言語: path/filepathとの良いお付き合い"
summary: "Go言語の持ち味であるクロスプラットフォーム対応を支えるパッケージの一つがpath/filepathです。このパッケージを使うことでOSごとに異なるセパレータ( / や \ )の扱いを恐れることなく、開発に立ち向かうことができます。提供されている機能は比較的シンプルで理解しやすいのですが、シンプルが故に、ふと躓く瞬間があるのではないでしょうか。本書では筆者の実体験における躓きをもとに、path/filepathパッケージの独自解説、迷わないお付き合いのしかたを紹介したいと思います。"
topics: ["go", "golang"]
published: true
price: 0
toc_depth: 2